/* administrateur */
CREATE TABLE administrateur ( id_uti IN identity(1, 1) NOT NULL);
alter table administrateur add constraint pk_admin PRIMARY KEY CLUSTERED (id_uti);


--###################### TABLE UTILISATEUR --######################--
create table Utilisateur (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY ,
NomDUtilisateur varchar2(10) not null,
psw varchar2(15) not null,
CONSTRAINT Pk_Utilisateur PRIMARY KEY (id)
);

